### ISSUE TITLE
unifont fails to load and fallback is the default font which is not monospace

### ISSUE THREAD

**Issue by eMBee** [lxsang/PTerm#4]
it looks like the pharo default font is loaded if the specified font fails to load.

pterm should select its own fallback font, or better try a list of fonts and use the best one that can be loaded.

**Comment by lxsang** [comment]
It is strange that the default font is used, because i force PTerm to download and use GNU Unifont (around 12 Mb). In case of fail, an error should be signalled. Are use sure you use the latest commits?

**Comment by eMBee** [comment]
yes, i updated the repo, and opened a new terminal that is now green. i can also see the unifont commits in the commit history. in the meantime i also verified that i can access the font url 
`http://unifoundry.com/pub/unifont/unifont-11.0.02/font-builds/unifont-11.0.02.ttf` so a network issue is less likely.

**Comment by lxsang** [comment]
So you use Pharo 7.0 on Mac or Linux ? I tried to reproduce the problem on Mac and Ubuntu 16.04, but no luck, it just works perfectly on my side.

**Comment by eMBee** [comment]
fedora 28 on Pharo-7.0.0+alpha.build.1346

**Comment by lxsang** [comment]
I have difficulty running pharo 7 on fedora 28 using Virtual Box (it crashes when I installed Pterm). Can you send me a screenshot of PTerm on your system, i doubt that the fallback font is actually Unifont, since it don't look really nice but I used it because it supports almost every UTF8 characters ( 65,536 code points). Bellow is the screenshot of PTerm with unifont:
![](https://github.com/lxsang/online_stuffs/raw/master/pterm_unifont.png)

Anyway, I will add an option that allows users to change the default font for PTerm

**Comment by eMBee** [comment]
i can't tell if the loading of unifont works. selecting the entry seems to do nothing. however with the font configurator working this unifont issue becomes a very low one. in fact i would suggest to remove this menu entry, and let the user themselves deal with adding non-standard fonts such as unifont if they want to use it.

**Comment by lxsang** [comment]
I just keep that menu entry for now, it will be removed in future update
